# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecount',
            name='imageHome',
            field=models.ImageField(blank=True, null=True, upload_to='imagecount/%Y/%m', verbose_name='\u8f6e\u64ad\u56fe'),
        ),
        migrations.AlterField(
            model_name='imagecount',
            name='imageHomeSmall',
            field=models.ImageField(blank=True, null=True, upload_to='imagecount/%Y/%m', verbose_name='\u5c0f\u8f6e\u64ad\u56fe'),
        ),
        migrations.AlterField(
            model_name='imagecount',
            name='imageRecommend',
            field=models.ImageField(blank=True, null=True, upload_to='imagecount/%Y/%m', verbose_name='\u9762\u5305\u5c51'),
        ),
    ]
