# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20180312_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='imageRecommend',
            field=models.ImageField(default=1, upload_to='interview/%Y/%m', verbose_name='\u5c01\u9762'),
            preserve_default=False,
        ),
    ]
