# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_interview_imagerecommend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='imageRecommend',
        ),
    ]
